#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and adds a custom response header

sudo apt update
sudo apt install -y haproxy

#edit /etc/haproxy/haproxy.cfg to add other settings

additional_settings=\
"
    frontend http-in
        bind *:80
        default_backend servers

    backend servers
        balance roundrobin
        server 6560-web-01 13.222.31.81:80 check
        server 6560-web-02 	34.204.67.32:80 check
        http-response set-header X-Served-By %[srv_name]
"
echo "$additional_settings" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init scripts

echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo service haproxy restart
