#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5452-webs
    bind *:80
    mode http
    balance roundrobin
    server 5487-web-01 54.163.92.47:80 check
    server 5487-web-02 44.202.151.248:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
